WebShop/Areas/Admin/Controllers/IconController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project.Models.DAO;
using WebShop.Helpers;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class IconController : Controller
    {
      
        
        [HttpGet("/Admin/Icon/Button")]
        public IActionResult Button()
        {
            //Session
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("Button");
        }

        [HttpGet("/Admin/Icon/Badges")]
        public IActionResult Badges()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("Badges");
        }


        [HttpGet("/Admin/Icon/Tabs")]
        public IActionResult Tabs()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("Tabs");
        }


        public IActionResult Cards()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("Cards");
        }


        [HttpGet("/Admin/Icon/Alerts")]
        public IActionResult Alerts()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("Alerts");
        }


        [HttpGet("/Admin/Icon/ProgressBars")]
        public IActionResult ProgressBars()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("ProgressBars");
        }


        [HttpGet("/Admin/Icon/Modals")]
        public IActionResult Modals()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("Modals");
        }


        [HttpGet("/Admin/Icon/Switchs")]
        public IActionResult Switchs()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("Switchs");
        }


        [HttpGet("/Admin/Icon/Grids")]
        public IActionResult Grids()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("Grids");
        }


        [HttpGet("/Admin/Icon/FontawesomeIcon")]
        public IActionResult FontawesomeIcon()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("FontawesomeIcon");
        }

       
    }
}

WebShop/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Models.DAO;
using ProjectCore.Models.DAO;
using WebShop.Models;
using System;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Facebook;
using Microsoft.AspNetCore.Session;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using WebShop.Helpers;
using System.Security.Cryptography;
using System.Text;
/*using ASPSnippets.GoogleAPI;*/
using System.Net;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http.Extensions;

namespace ProjectCore.Controllers
{
    public class UserController : Controller
    {
        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.GetEncodedUrl());
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        public IActionResult Index()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View();
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDAO();
                if (dao.isExistsUser(model.taikhoan))
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại");
                }
                else
                {
                    var kh = new khachhang();
                    kh.taikhoan = model.taikhoan;
                    kh.matkhau = encryption(model.matkhau);
                    kh.email = model.email;
                    kh.sdt = model.sdt;
                    kh.hoten = model.hoten;
                    kh.diachi = model.diachi;
                    kh.roleTableid = 1;
                    var stringUser = JsonConvert.SerializeObject(kh);
                    string ranString = createRandomString();
                    string body = "ma xac thuc cua ban la" + ranString;
                    ViewBag.stringUser = stringUser;
                    ViewBag.ranString = ranString;
                    new MailHelper().sendMail(model.email,"xac thuc email",body);
                    return View("ConfirmMail");
                }
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult showUserInfor()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("inforUser");
        }
        [HttpGet]
        public ActionResult ChangePassword()
        {
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View("ConfirmPassword");
        }
        [HttpPost]
        public ActionResult ConfirmPassword(ChangePasswordModel model,string taikhoan)
        {
            if (ModelState.IsValid)
            {
                var ud = new UserDAO();
                string mk = model.matkhau;
                ud.updatePassword(taikhoan, encryption(mk));
                return View("Login");
            }
            var user = SessionHelper.GetObjectFromJson<khachhang>(HttpContext.Session, "User_Session");
            ViewBag.user = user;
            return View(model);
        }
        [HttpPost]
        public ActionResult ChangeUserInfor(changeInforModel model,string id)
        {
            if (ModelState.IsValid)
            {
                int numid = Int32.Parse(id);
                var ud = new UserDAO();
                ud.updatePersonalInfor(numid, model.sdt, model.email, model.diachi, model.hoten);
                var kh = ud.getUser(numid);
                SessionHelper.setObjectAsJson(HttpContext.Session, "User_Session", kh);
                return RedirectToAction("showUserInfor");
            }
            return RedirectToAction("showUserInfor");
        }
        [HttpGet]
        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = "1209214939431822",
                client_secret = "13d54191c846d58191b93b25ee295daa",
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }
        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = "1209214939431822",
                client_secret = "13d54191c846d58191b93b25ee295daa",
                redirect_uri = RedirectUri.AbsoluteUri,
                code
            });


            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                // Get the user's information, like email, first name, middle name etc
                dynamic me = fb.Get("me?fields=first_name,last_name,id,phone");
                string email = me.email;

                var kh = new khachhang();
                kh.taikhoan = email;
                kh.email = email;
                string pass = encryption(email);
                kh.matkhau = pass;
                UserDAO ud =  new UserDAO();
                ud.insertUser(kh);
                SessionHelper.setObjectAsJson(HttpContext.Session, "User_Session", kh);

            }
            return Redirect("/");
        }
        [HttpPost]
        public void LoginWithGooglePlus()
        {
           /* GoogleConnect.ClientId = "831581208531-6rl0srsg18if16a6mcij9uhau2g90nsc.apps.googleusercontent.com";
            GoogleConnect.ClientSecret = "bctO56iTrnMnumggjBnA3S2D";
           // GoogleConnect.RedirectUri = Request.Url.AbsoluteUri.Split('?')[0];
            GoogleConnect.Authorize("profile", "email");*/
        }
        public IActionResult InsertUser(string mailConfirm,string khachhangInfor,string ranString)
        {
            if (mailConfirm.Equals(ranString))
            {
                khachhang kh =JsonConvert.DeserializeObject<khachhang>(khachhangInfor);
                var dao = new UserDAO();
                dao.insertUser(kh);
                return Redirect("Login");
            }
            String errors = "ten dang nhap khong chinh xac";
            ViewBag.errors = errors;
            return Redirect("ConfirmMail");
        }
        [HttpPost]
        public IActionResult Login(LoginModel model)
        {

            if (ModelState.IsValid)
            {
                var dao = new UserDAO();
                var result = dao.checkUser(model.taikhoan, encryption(model.matkhau));
                if (result == 1)
                {
                    var user = dao.GetById(model.taikhoan);
                    var userSession = new khachhang();
                    userSession.id = user.id;
                    userSession.taikhoan = user.taikhoan;
                    userSession.email = user.email;
                    userSession.hoten = user.hoten;
                    userSession.diachi = user.diachi;
                    userSession.sdt = user.sdt;
                    userSession.roleTableid = user.roleTableid;
                    //String objectAsString = JsonConvert.SerializeObject(userSession);
                    //HttpContext.Session.SetString("User_Session", objectAsString);
                    SessionHelper.setObjectAsJson(HttpContext.Session, "User_Session", userSession);
                    return Redirect("/");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Mật khẩu không chính xác.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }

            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("User_Session");
            return Redirect("/");
        }
        [HttpGet]
        public IActionResult viewForgotPassword()
        {
            return View("ForgotPassword");
        }
        [HttpPost]
        public IActionResult forgotPassword(string username)
        {
            UserDAO ud = new UserDAO();
            var user = ud.GetById(username);
            String newPass = createRandomString();
            ud.updatePassword(user.taikhoan, encryption(newPass));
            
            string body = "mat khau moi cua ban la: " + newPass + " hoac truy cap vao duong link sau de lay lai mat khau:"+ "https://localhost:44334/User/Login";
            var emailString = user.email;
            new MailHelper().sendMail(emailString,"Quen mat khau",body);
            return View("Login");
        }
        public string encryption(string password)
        {
            MD5CryptoServiceProvider md5 = new MD5CryptoServiceProvider();
            byte[] encrypt;
            UTF8Encoding encode = new UTF8Encoding();
            StringBuilder encryptdata = new StringBuilder();
            encrypt = md5.ComputeHash(encode.GetBytes(password));
            for (int i = 0; i < encrypt.Length; i++)
            {
                encryptdata.Append(encrypt[i].ToString());
            }
            return encryptdata.ToString();
        }

WebShop/Areas/Admin/Views/Shared/_MasterLayout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    var user = ViewBag.user;

}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Creepy">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <!-- Fontfaces CSS-->
    <link href="~/Admin/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/Admin/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/Admin/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Admin/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- FullCalendar -->
    <link href='~/Admin/vendor/fullcalendar-3.10.0/fullcalendar.css' rel='stylesheet' media="all" />

    <!-- Main CSS-->
    <link href="~/Admin/css/theme.css" rel="stylesheet" media="all">

</head>

<body class="animsition">

    <div class="page-wrapper">
        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <img src="~/Admin/images/icon/logo.png" alt="Web Admin" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li>
                            <a asp-area="Admin" asp-controller="Home" asp-action="Admin">
                                <i class="fas fa-chart-bar"></i>Home
                            </a>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="Chart" asp-action="Index">
                                <i class="fas fa-chart-bar"></i>Charts
                            </a>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="Table" asp-action="Index">
                                <i class="fas fa-table"></i>Tables
                            </a>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="Form" asp-action="Index">
                                <i class="far fa-check-square"></i>Forms
                            </a>
                        </li>
                        <li>
                            <a asp-area="Admin" asp-controller="Calendar" asp-action="Index">
                                <i class="fas fa-calendar-alt"></i>Calendar
                            </a>
                        </li>                                               
                        <li class="has-sub">
                            <a class="js-arrow" href="#">
                                <i class="fas fa-desktop"></i>UI Elements
                            </a>
                            <ul class="list-unstyled navbar__sub-list js-sub-list">
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="Button">Button</a>                                                      
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="Badges">Badges</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="Tabs">Tabs</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="Cards">Cards</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="Alerts">Alerts</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="ProgressBars">Progress Bars</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="Modals">Modals</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="Switchs">Switchs</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="Grids">Grids</a>
                                </li>
                                <li>
                                    <a asp-area="Admin" asp-controller="Icon" asp-action="FontawesomeIcon">Fontawesome Icon</a>
                                </li>                               
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <form class="form-header" action="" method="POST">
                                <input class="au-input au-input--xl" type="text" name="search" placeholder="Search for datas &amp; reports..." />
                                <button class="au-btn--submit" type="submit">
                                    <i class="zmdi zmdi-search"></i>
                                </button>
                            </form>
                            <div class="header-button">
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            <img src="~/Admin/images/icon/avatar-01.jpg" alt="@user.taikhoan" />
                                        </div>
                                        <div class="content">
                                            <a class="js-acc-btn" href="#">@user.taikhoan</a>
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                    <a href="#">
                                                        <img src="~/Admin/images/avatar.jpg" alt=@user.taikhoan />
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        <a href="#">@user.taikhoan</a>
                                                    </h5>
                                                    <span class="email">@user.email</span>
                                                </div>
                                            </div>
                                            <div class="account-dropdown__body">
                                                <div class="account-dropdown__item">
                                                    <a asp-controller="User" asp-action="showUserInfor">
                                                        <i class="zmdi zmdi-account"></i>Account
                                                    </a>
                                                </div>
                                                <div class="account-dropdown__item">
                                                    <a href="#">
                                                        <i class="zmdi zmdi-settings"></i>Setting
                                                    </a>
                                                </div>
                                                <div class="account-dropdown__item">
                                                    <a href="#">
                                                        <i class="zmdi zmdi-money-box"></i>Billing
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="account-dropdown__footer">
                                                <a asp-controller="User" asp-action="Logout">
                                                    <i class="zmdi zmdi-power"></i>Logout
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- HEADER DESKTOP-->
            <!-- MAIN CONTENT-->
            <div class="main-content">
                @RenderBody()
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="~/Admin/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="~/Admin/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Admin/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/Admin/vendor/slick/slick.min.js">
    </script>
    <script src="~/Admin/vendor/wow/wow.min.js"></script>
    <script src="~/Admin/vendor/animsition/animsition.min.js"></script>
    <script src="~/Admin/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="~/Admin/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Admin/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="~/Admin/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Admin/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Admin/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Admin/vendor/select2/select2.min.js">

    </script>
   

    <!-- full calendar requires moment along jquery which is included above -->
    <script src="~/Admin/vendor/fullcalendar-3.10.0/lib/moment.min.js"></script>
    <script src="~/Admin/vendor/fullcalendar-3.10.0/fullcalendar.js"></script>

    <!-- Main JS-->
    <script src="~/Admin/js/main.js"></script>


    <script type="text/javascript">
        $(function () {
            // for now, there is something adding a click handler to 'a'
            var tues = moment().day(2).hour(19);

            // build trival night events for example data
            var events = [
                {
                    title: "Special Conference",
                    start: moment().format('YYYY-MM-DD'),
                    url: '#'
                },
                {
                    title: "Doctor Appt",
                    start: moment().hour(9).add(2, 'days').toISOString(),
                    url: '#'
                }

            ];

            var trivia_nights = []

            for (var i = 1; i <= 4; i++) {
                var n = tues.clone().add(i, 'weeks');
                console.log("isoString: " + n.toISOString());
                trivia_nights.push({
                    title: 'Trival Night Pub XYZ',
                    start: n.toISOString(),
                    allDay: false,
                    url: '#'
                });
            }

            // setup a few events
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay,listWeek'
                },
                events: events.concat(trivia_nights)
            });
        });
    </script>

</body>

</html>
<!-- end document-->